from Trie import *
T=Trie()
insert(T,"HOLA")
insert(T,"HOPA")
insert(T,"HOKI")
insert(T,"HOME")
insert(T,"HOMERO")
insert(T,"MARTINA")
insert(T,"AIDA")
#insert(T,"EMOH")
"""P=Trie()
insert(P,"HOLA")
insert(P,"HOPA")
insert(P,"HOKI")
insert(P,"HOME")
insert(P,"HOMERO")
insert(P,"MARTINA")
insert(P,"AIDA")
insert(P,"MALENA")
insert(P,"LANA")
insert(P,"MALA")
insert(P,"ENOJADA")
palabras1=get_words(T)
palabras2=get_words(P)
print(palabras1)
print(palabras2)
print(is_sublist(palabras1, palabras2))"""

#palabras=patron(T,"HO",4)
#print(palabras)
print(palabras_invertidas(T))